title: Model Plan for a District Post-Yard, Russian Empire (1782)
email: jwr@illinois.edu
description: John Randolph (University of Illinois Urbana-Champaign

baseurl: "/MinSample" # the subpath of your site. Change it if the name of your repository is other than "mindoc"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
